spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
server:
  servlet:
    encoding:
      force-response: true
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/main034?serverTimezone=Asia/Seoul
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}

logging:
  level:
    org:
      springframework:
      orm:
        jpa: DEBUG
jwt:
  key: GlFU9fJQv7qL6pIcxQQwHZe1WQIeja6Cpt6WKjFEPcYMhKm2LEkj4xbKdA3안녕하세요반갑습니다
# key: ${JWT_SECRET_KEY} #민감한 정보는 시스템 환경변수에서 로드함
  access-token-expiration-minutes: 30 #30분
  refresh-token-expiration-minutes: 420 # 420분

mail:
  address:
    admin: admin@gmail.com