spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver4
    url:
    username:
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
server:
  servlet:
    encoding:
      force-response: true

logging:
  level:
    org:
      springframework:
      orm:
        jpa: DEBUG
jwt:
  key:
  # key: ${JWT_SECRET_KEY} #민감한 정보는 시스템 환경변수에서 로드함
  access-token-expiration-minutes: 30 #30분
  refresh-token-expiration-minutes: 420 # 420분

mail:
  address:
    admin: admin@gmail.com